name: Build Kivy APK/AAB

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: kivymd/buildozer-action@master
        with:
          buildozer_version: stable
        env:
          # تأكد من أن ملف buildozer.spec في المجلد الرئيسي للمشروع
          # سيقوم Buildozer بقراءة المتطلبات من هناك تلقائياً
          LOG_LEVEL: 2

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*

